---
language: python
python: "2.7"
env:
  matrix:
    - ANSIBLE_VERSION="2.3"
    - ANSIBLE_VERSION="2.7.0"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible=="$ANSIBLE_VERSION"
script:
  - echo localhost > inventory
  - ansible-playbook -i inventory test.yml --syntax-check
  - ansible-playbook -i inventory test.yml --connection=local --become
  - >
    ansible-playbook -i inventory test.yml --connection=local --become
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
